"""P01 corpus builder. Deterministic, host-side, no oracle calls.

Resolves the repository root from this script's own location (no host paths
hard-coded). The frozen upstream Linguist checkout is provided via
--upstream, never guessed.

Rule for large tier: for each of the first 64 languages (alphabetically by
samples/ dir name), pick the first eligible file (alphabetically) that is a
regular file 0 < size <= 16 KiB. Deterministic given the frozen upstream tree.
"""
import argparse, hashlib, json, shutil
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "evidence" / "phases" / "P01" / "corpus"
FILES = OUT / "files"
REPOS = OUT / "repos"


def sha256(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def write(rel: str, content: str) -> None:
    """Write text fixture with exact LF endings, UTF-8, no BOM."""
    p = FILES / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_bytes(content.encode("utf-8"))


def build(upstream: Path) -> None:
    if FILES.exists(): shutil.rmtree(FILES)
    if REPOS.exists(): shutil.rmtree(REPOS)
    FILES.mkdir(parents=True)

    # --- A: extension-driven -------------------------------------------------
    write("a_ext/hello_py.py", 'print("hello")\n')
    write("a_ext/hello_rb.rb", 'puts "hello"\n')
    write("a_ext/hello_js.js", 'console.log("hello");\n')
    write("a_ext/hello_c.c", '#include <stdio.h>\n\nint main(void) {\n    return 0;\n}\n')
    write("a_ext/hello_go.go", 'package main\n\nfunc main() {}\n')
    write("a_ext/hello_rs.rs", 'fn main() {}\n')
    # Malbolge sample copied verbatim from the frozen upstream (no trailing newline)
    shutil.copyfile(
        upstream / "samples" / "Malbolge" / "truth_machine.malbolge",
        FILES / "a_ext" / "truth_machine.malbolge",
    )

    # --- B: filename-driven --------------------------------------------------
    write("b_filename/gemfile/Gemfile", 'source "https://rubygems.org"\n\ngem "rails"\n')
    write("b_filename/dockerfile/Dockerfile", 'FROM scratch\nCOPY . /\n')
    write("b_filename/makefile/Makefile", 'all:\n\t@echo hello\n')
    write("b_filename/cmake/CMakeLists.txt", 'cmake_minimum_required(VERSION 3.10)\nproject(x)\n')

    # --- D: shebang ----------------------------------------------------------
    write("d_shebang/py_script", '#!/usr/bin/env python\nprint("hello")\n')
    write("d_shebang/pl_script", '#!/usr/bin/env perl\nprint "hello\\n";\n')
    write("d_shebang/sh_script.sh", '#!/usr/bin/env sh\necho hello\n')

    # --- E: modeline ---------------------------------------------------------
    write("e_modeline/emacs_py.txt", '# -*- mode: python -*-\nprint("hello")\n')
    write("e_modeline/vim_js.txt", '/* vim: ft=javascript: */\nconsole.log("hello");\n')
    write("e_modeline/emacs_ruby.txt", '# -*- ruby -*-\nputs "hello"\n')

    # --- F: ambiguous extensions / heuristics --------------------------------
    write("f_ambig/pl_perl.pl", 'use strict;\nprint "hello\\n";\n')
    write("f_ambig/pl_prolog.pl", 'hello_world :- format("hello~n").\n')
    write("f_ambig/h_objc.h", '#import <Foundation/Foundation.h>\n\n@interface Thing\n@end\n')
    write("f_ambig/h_cpp.h", '#include <vector>\n\nnamespace ns {\ntemplate <class T> T f(T x) { return x; }\n}\n')

    # --- G: vendor / generated / documentation --------------------------------
    write("g_flags/vendor_positive/node_modules/jquery.js", 'console.log("jquery placeholder");\n')
    write("g_flags/vendor_negative/index.js", 'console.log("application code");\n')
    write("g_flags/generated_positive/Cargo.lock", '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n')
    write("g_flags/generated_negative/main.rs", 'fn main() { println!("x"); }\n')
    write("g_flags/documentation_positive/README.md", '# Project\n\nThis is documentation.\n')
    write("g_flags/documentation_negative/app.py", 'print("x")\n')

    # --- H: repository fixtures ----------------------------------------------
    def repo_files(name: str, entries: dict) -> None:
        r = REPOS / name
        r.mkdir(parents=True, exist_ok=True)
        for rel, content in entries.items():
            p = r / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_bytes(content.encode("utf-8"))

    repo_files("repo_micro", {"hello.py": 'print("hello")\n'})
    repo_files("repo_mixed", {
        "main.py": 'print("py")\n',
        "app.js": 'console.log("js");\n',
        "tool.rb": 'puts "rb"\n',
    })
    repo_files("repo_filtered", {
        "main.py": 'print("py")\n',
        "node_modules/pkg/index.js": 'console.log("vendored");\n',
        "Cargo.lock": '# This file is automatically @generated by Cargo.\nversion = 4\n',
        "README.md": '# Docs\n\nDocumentation here.\n',
    })

    # --- I: large tier --------------------------------------------------------
    tier_entries = []
    samples = upstream / "samples"
    for lang_dir in sorted(p for p in samples.iterdir() if p.is_dir())[:64]:
        for f in sorted(lang_dir.rglob("*")):
            if f.is_file() and not f.is_symlink() and 0 < f.stat().st_size <= 16384:
                rel_src = f.relative_to(upstream)
                dest = FILES / "tier" / rel_src
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(f, dest)
                tier_entries.append(rel_src.as_posix())
                break

    # --- manifest -------------------------------------------------------------
    rows = []

    def add(rel: str, tags: list, source: str, src_ref=None) -> None:
        p = FILES / rel
        rows.append({
            "id": rel.replace("/", "__"),
            "coverage_tags": sorted(tags),
            "relative_path": f"corpus/files/{rel}",
            "size_bytes": p.stat().st_size,
            "sha256": sha256(p),
            "source": source,
            "source_reference": src_ref,
        })

    add("a_ext/hello_py.py", ["extension"], "p01_fixture")
    add("a_ext/hello_rb.rb", ["extension"], "p01_fixture")
    add("a_ext/hello_js.js", ["extension"], "p01_fixture")
    add("a_ext/hello_c.c", ["extension"], "p01_fixture")
    add("a_ext/hello_go.go", ["extension"], "p01_fixture")
    add("a_ext/hello_rs.rs", ["extension"], "p01_fixture")
    add("a_ext/truth_machine.malbolge", ["extension", "malbolge_patch"], "upstream_sample", "samples/Malbolge/truth_machine.malbolge")
    add("b_filename/gemfile/Gemfile", ["filename"], "p01_fixture")
    add("b_filename/dockerfile/Dockerfile", ["filename"], "p01_fixture")
    add("b_filename/makefile/Makefile", ["filename"], "p01_fixture")
    add("b_filename/cmake/CMakeLists.txt", ["filename"], "p01_fixture")
    add("d_shebang/py_script", ["shebang"], "p01_fixture")
    add("d_shebang/pl_script", ["shebang"], "p01_fixture")
    add("d_shebang/sh_script.sh", ["shebang"], "p01_fixture")
    add("e_modeline/emacs_py.txt", ["modeline"], "p01_fixture")
    add("e_modeline/vim_js.txt", ["modeline"], "p01_fixture")
    add("e_modeline/emacs_ruby.txt", ["modeline"], "p01_fixture")
    add("f_ambig/pl_perl.pl", ["heuristic"], "p01_fixture")
    add("f_ambig/pl_prolog.pl", ["heuristic"], "p01_fixture")
    add("f_ambig/h_objc.h", ["heuristic"], "p01_fixture")
    add("f_ambig/h_cpp.h", ["heuristic"], "p01_fixture")
    add("g_flags/vendor_positive/node_modules/jquery.js", ["vendor", "vendor_positive"], "p01_fixture")
    add("g_flags/vendor_negative/index.js", ["vendor", "vendor_negative"], "p01_fixture")
    add("g_flags/generated_positive/Cargo.lock", ["generated", "generated_positive"], "p01_fixture")
    add("g_flags/generated_negative/main.rs", ["generated", "generated_negative"], "p01_fixture")
    add("g_flags/documentation_positive/README.md", ["documentation", "documentation_positive"], "p01_fixture")
    add("g_flags/documentation_negative/app.py", ["documentation", "documentation_negative"], "p01_fixture")
    for rel_src in tier_entries:
        add(f"tier/{rel_src}", ["large_tier"], "upstream_sample", rel_src)

    repos_rows = []
    for repo in ["repo_micro", "repo_mixed", "repo_filtered"]:
        rdir = REPOS / repo
        rentries = []
        for f in sorted(rdir.rglob("*")):
            if f.is_file():
                rel = f.relative_to(rdir).as_posix()
                rentries.append({
                    "relative_path": rel,
                    "size_bytes": f.stat().st_size,
                    "sha256": sha256(f),
                })
        repos_rows.append({
            "id": repo,
            "coverage_tags": ["repo_aggregation"],
            "files": rentries,
        })

    manifest = {
        "schema": "p01-corpus-manifest/1",
        "generated_by": "scripts/p01_build_corpus.py",
        "files": sorted(rows, key=lambda r: r["id"]),
        "metadata_languages": ["Malbolge", "Python", "Ruby", "JavaScript"],
        "repos": repos_rows,
    }
    mp = OUT / "manifest.json"
    mp.parent.mkdir(parents=True, exist_ok=True)
    mp.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({"files": len(rows), "large_tier": sum(1 for r in rows if "large_tier" in r["coverage_tags"])}))
    print(f"manifest: {mp}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--upstream", required=True,
                    help="Path to the frozen Linguist checkout (contains samples/).")
    build(Path(ap.parse_args().upstream))
