"""P02 verification script. Checks the invariants the roadmap requires:

  INVARIANT_A: every graph edge is present in at least one normalized trace.
  INVARIANT_B: node frequency == count of its events across all traces.
  INVARIANT_C: every graph node has at least one trace case that contains it.
  INVARIANT_D: terminal language per case in trace == P01 frozen
               oracle language for that case (unless it's a repo case,
               where we compare aggregated language-bytes totals).

Also checks determinism: the same graph regenerates from either run.
Prints PASS/FAIL counts and exits non-zero on any failure.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path


def load_json(p: Path):
    return json.loads(p.read_text(encoding="utf-8"))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--traces", required=True)
    ap.add_argument("--traces-b", default=None, help="Second run for determinism")
    ap.add_argument("--graph", required=True)
    ap.add_argument("--graph-b", default=None, help="Second-run graph for determinism")
    ap.add_argument("--p01", required=True,
                    help="P01 frozen normalized oracle output")
    ap.add_argument("--parity", required=True,
                    help="P02 terminal-parity JSON generated by the tracer")
    args = ap.parse_args()

    traces = load_json(Path(args.traces))
    graph = load_json(Path(args.graph))
    p01 = load_json(Path(args.p01))
    parity = load_json(Path(args.parity))

    failures = []

    # INVARIANT_A: every edge is backed by at least one trace adjacency.
    edge_index = {}
    for case in traces["traces"]:
        events = case["events"]
        for i in range(1, len(events)):
            a = events[i - 1]["operation"]
            b = events[i]["operation"]
            if a != b:
                edge_index.setdefault((a, b), 0)
                edge_index[(a, b)] += 1

    for edge in graph["edges"]:
        key = (edge["from"], edge["to"])
        if key not in edge_index:
            failures.append(f"edge without trace backing: {key}")

    # INVARIANT_B: observed_frequency == count of events of that op.
    freq = {}
    for case in traces["traces"]:
        for ev in case["events"]:
            freq[ev["operation"]] = freq.get(ev["operation"], 0) + 1
    for node in graph["operations"]:
        want = freq.get(node["id"], 0)
        if node["observed_frequency"] != want:
            failures.append(f"frequency mismatch in {node['id']}: graph={node['observed_frequency']} expected={want}")

    # INVARIANT_C: every node has at least one case containing that op.
    case_ops = {c["case_id"]: {e["operation"] for e in c["events"]} for c in traces["traces"]}
    for node in graph["operations"]:
        found = False
        for cid, ops in case_ops.items():
            if node["id"] in ops:
                found = True
                break
        if not found:
            failures.append(f"node with no backing case: {node['id']}")
        if node["id"] not in freq:
            # borrow check: also make sure frequency agrees with counting
            pass

    # INVARIANT_D: terminal parity matches P01 for file cases.
    p01_files = {k: v["language"] for k, v in p01["files"].items()}
    for case in traces["traces"]:
        if case["kind"] != "file":
            continue
        exp = p01_files.get(case["case_id"])
        if exp != case["terminal_language"]:
            failures.append(f"terminal parity mismatch in {case['case_id']}: p01={exp} p02={case['terminal_language']}")

    # Terminal parity summary emitted by the tracer itself must be all-true.
    mismatch_cases = [c for c in parity["cases"] if not c["equal"]]
    if mismatch_cases:
        failures.append(f"tracer reports {len(mismatch_cases)} mismatch(es): " +
                        ", ".join(c["case_id"] for c in mismatch_cases))

    # Determinism between run A and run B, when supplied.
    if args.graph_b:
        g2 = load_json(Path(args.graph_b))
        if json.dumps(graph, sort_keys=True) != json.dumps(g2, sort_keys=True):
            failures.append("graph from run 1 != graph from run 2")
    if args.traces_b:
        t2 = load_json(Path(args.traces_b))
        if json.dumps(traces, sort_keys=True) != json.dumps(t2, sort_keys=True):
            failures.append("traces run 1 != traces run 2 (normalized comparison)")

    print("INVARIANT_A edge trace backing:    " + ("PASS" if all(not f.startswith("edge without") for f in failures) else "FAIL"))
    print("INVARIANT_B frequency:             " + ("PASS" if all(not f.startswith("frequency") for f in failures) else "FAIL"))
    print("INVARIANT_C node backing:          " + ("PASS" if all(not f.startswith("node with no") for f in failures) else "FAIL"))
    print("INVARIANT_D terminal parity:      " + ("PASS" if all("parity mismatch" not in f for f in failures) else "FAIL"))
    if args.graph_b or args.traces_b:
        print("DETERMINISM:                      " + ("PASS" if all(not f.startswith("graph from") and not f.startswith("traces") for f in failures) else "FAIL"))

    total = len(failures)
    ok = len(failures) == 0
    print(f"CHECK RESULT: {'PASS' if ok else 'FAIL'} ({total} failure{'s' if total != 1 else ''})")
    for f in failures:
        print(f"  - {f}")

    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
